cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: srini-s3bucket-demo
    
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

server:
  port: 9091
